[tool.poetry]
name = "ucluster"
version = "0.3.2"
description = "Text-based clustering utility"
authors = ["R. Miles McCain <github@sendmiles.email>"]
packages = [
    { include = "ucluster" }
]

[tool.poetry.dependencies]
python = "^3.8"
fasttext = "^0.9.2"
nltk = "^3.7"
loguru = "^0.6.0"
hdbscan = "^0.8.29"
visidata = "^2.10"

[tool.poetry.dev-dependencies]
black = "^21.11b1"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry2conda]
name = "ucluster"
