[tool.poetry]
name = "ucluster"
version = "0.1.0"
description = "User clustering utility"
authors = ["R. Miles McCain <github@sendmiles.email>"]
packages = [
    { include = "ucluster" }
]

[tool.poetry.dependencies]
python = "^3.8"
networkx = "^2.6.3"
fasttext = "^0.9.2"
scikit-learn = "^1.0.1"
nltk = "^3.6.5"
loguru = "^0.5.3"
pyclustering = "^0.10.1"
hdbscan = "^0.8.27"

[tool.poetry.dev-dependencies]
black = "^21.11b1"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
